name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    name: Unit Testing

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
